import { readFile } from 'node:fs/promises'
import type { Page } from '@playwright/test'
import { test, expect, attachScreenshot, expectNoOverflow, openWorkspace, readRecords, seedWorkspace, showFullPrompt, showPromptDiff, showPromptEditor, TASK_ID } from './fixtures'

const CURRENT = 'Summarize a customer support message in one sentence.\nKeep the request and deadline.'
const PROPOSED = 'Summarize a customer support message in one sentence.\nPreserve the customer’s request and any explicit deadline. Do not add details.'

async function expectStored(page: Page, expected: string) {
  await expect.poll(async () => (await readRecords(page, 'tasks')).find((task) => task.id === TASK_ID)?.initialPrompt).toBe(expected)
}

async function typePrompt(page: Page, text: string) {
  const editor = await showPromptEditor(page)
  await editor.focus()
  await page.keyboard.press('ControlOrMeta+A')
  await page.keyboard.insertText(text)
  await expect.poll(async () => (await editor.locator('.cm-line').allTextContents()).join('\n')).toBe(text)
}

async function expectSmallDiff(page: Page) {
  await expect(page.getByTestId('prompt-diff')).toHaveAttribute('data-exact', 'true')
  const summary = page.getByTestId('prompt-diff-summary')
  await expect(summary).toHaveAttribute('data-unchanged', '1')
  await expect(summary).toHaveAttribute('data-removed', '1')
  await expect(summary).toHaveAttribute('data-added', '1')
  await expect(page.getByTestId('prompt-diff-row')).toHaveCount(3)
}

test('revision shows an exact accessible diff and keep-current preserves the source', async ({ page }, info) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await seedWorkspace(page, { taskName: 'Support summary', runCount: 1, candidatesPerRun: 2, initialPrompt: CURRENT, bestPrompt: PROPOSED })
  await openWorkspace(page)
  expect(await (await showFullPrompt(page)).textContent()).toBe(PROPOSED)
  await expect(page.getByTestId('prompt-diff')).toHaveCount(0)
  await attachScreenshot(page, info, 'concept-guided-revision', false)
  await showPromptDiff(page)
  await expectSmallDiff(page)
  const unchanged = page.locator('[data-testid="prompt-diff-row"][data-kind="unchanged"]')
  const removed = page.locator('[data-testid="prompt-diff-row"][data-kind="removed"]')
  const added = page.locator('[data-testid="prompt-diff-row"][data-kind="added"]')
  await expect(unchanged.locator('.line-text')).toHaveText(CURRENT.split('\n')[0])
  await expect(removed.locator('.line-text')).toHaveText('Keep the request and deadline.')
  await expect(added.locator('.line-text')).toHaveText(PROPOSED.split('\n')[1])
  await expect(removed.locator('.sr-only')).toContainText('removed')
  await expect(added.locator('.sr-only')).toContainText('added')
  await expect(page.getByTestId('prompt-diff-limited')).toHaveCount(0)
  await expectNoOverflow(page)
  await attachScreenshot(page, info, 'two-line-diff-disclosure', false)

  await page.getByTestId('original-wording').locator('summary').press('Enter')
  expect(await page.getByTestId('result-prompt').textContent()).toBe(PROPOSED)
  await expect(page.getByTestId('prompt-diff')).toHaveCount(0)
  await page.getByTestId('original-wording').locator('summary').press('Enter')
  await expectSmallDiff(page)
  await page.getByRole('button', { name: 'Keep current', exact: true }).click()
  const editor = await showPromptEditor(page)
  await expect.poll(async () => (await editor.locator('.cm-line').allTextContents()).join('\n')).toBe(CURRENT)
  await expectStored(page, CURRENT)
  await expect(page.getByRole('button', { name: 'Undo last apply', exact: true })).toHaveCount(0)
  await page.getByTestId('run-result').getByRole('button', { name: 'Review changes', exact: true }).press('Enter')
  await showPromptDiff(page)
  await expectSmallDiff(page)
  expect(await page.evaluate(() => matchMedia('(prefers-reduced-motion: reduce)').matches)).toBe(true)
})

test('apply and undo are exact across reload, and later edits invalidate stale undo', async ({ page }, info) => {
  const before = `${CURRENT}\n\nKeep {order_id} exactly. Пример 🙂`
  const after = `${PROPOSED}\n\nKeep {order_id} exactly. Пример 🙂`
  await seedWorkspace(page, { runCount: 1, candidatesPerRun: 2, initialPrompt: before, bestPrompt: after })
  await openWorkspace(page)
  await expect(page.getByTestId('result-prompt')).toBeVisible()
  await page.getByRole('button', { name: 'Use this revision', exact: true }).click()
  await expectStored(page, after)
  await expect(page.getByRole('button', { name: 'Undo last apply', exact: true })).toBeEnabled()
  await page.reload()
  await expect(page.getByTestId('run-status')).toHaveAttribute('data-status', 'completed')
  await expect(page.getByRole('button', { name: 'Undo last apply', exact: true })).toBeEnabled()
  await expectStored(page, after)
  await attachScreenshot(page, info, 'applied-revision-with-undo', false)
  await page.getByRole('button', { name: 'Undo last apply', exact: true }).press('Enter')
  await expectStored(page, before)
  await expect(page.getByRole('button', { name: 'Undo last apply', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Use this revision', exact: true }).click()
  await expectStored(page, after)
  const manual = `${after}\nMy later edit must never be overwritten by stale Undo.`
  await typePrompt(page, manual)
  await expect(page.getByRole('button', { name: 'Undo last apply', exact: true })).toHaveCount(0)
  await expectStored(page, manual)
  await page.reload()
  await expect(page.getByTestId('run-status')).toHaveAttribute('data-status', 'completed')
  await expect(page.getByRole('button', { name: 'Undo last apply', exact: true })).toHaveCount(0)
  const editor = await showPromptEditor(page)
  await expect.poll(async () => (await editor.locator('.cm-line').allTextContents()).join('\n')).toBe(manual)
  await expectStored(page, manual)
})

test('one-next-step flow preserves the brief through setup and ends in review', async ({ page }, info) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Improve prompt', exact: true }).first().click()
  await typePrompt(page, CURRENT)
  const workspace = page.getByTestId('workspace-ready')
  await expect(workspace.locator('.btn.primary:visible')).toHaveCount(1)
  await expect(page.getByRole('button', { name: 'Choose models', exact: true })).toBeEnabled()
  await expect(page.getByRole('navigation', { name: 'Prompt improvement steps', exact: true }).getByRole('button', { name: /Review changes/ })).toBeDisabled()
  await page.getByRole('button', { name: 'Choose models', exact: true }).click()
  const configuration = page.getByRole('dialog', { name: 'Configure models', exact: true })
  await expect(configuration).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(configuration).toBeHidden()
  await expect(page.getByRole('button', { name: 'Choose models', exact: true })).toBeFocused()
  await page.getByRole('button', { name: 'Choose models', exact: true }).press('Enter')
  await configuration.getByRole('button', { name: 'Use demo', exact: true }).click()
  await configuration.getByRole('button', { name: 'Save models', exact: true }).click()
  const editor = await showPromptEditor(page)
  await expect.poll(async () => (await editor.locator('.cm-line').allTextContents()).join('\n')).toBe(CURRENT)
  expect(await readRecords(page, 'runs')).toHaveLength(0)
  await expect(workspace.locator('.btn.primary:visible')).toHaveCount(1)
  await expect(page.getByRole('button', { name: 'Improve prompt', exact: true })).toBeEnabled()
  await page.getByRole('button', { name: 'Improve prompt', exact: true }).click()
  await expect(page.getByTestId('run-status')).toHaveAttribute('data-status', 'running')
  await expect(page.getByRole('button', { name: 'Use this revision', exact: true })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Configure models', exact: true })).toBeDisabled()
  await expect(page.getByTestId('run-status')).toHaveAttribute('data-status', 'completed', { timeout: 30_000 })
  await expect(page.getByTestId('result-prompt')).toBeVisible()
  await expect(page.getByTestId('prompt-diff')).toHaveCount(0)
  await expect(page.getByRole('textbox', { name: 'Your prompt', exact: true })).toHaveCount(0)
  await expect(workspace.locator('.btn.primary:visible')).toHaveCount(1)
  await expect(page.getByRole('button', { name: 'Use this revision', exact: true })).toBeEnabled()
  await expectNoOverflow(page)
  await attachScreenshot(page, info, 'stepwise-completed-revision', false)
})

test('long replacement diff stays bounded while export, apply, and undo keep all text', async ({ page }, info) => {
  const before = Array.from({ length: 5_000 }, (_, index) => `Original line ${index}: ${'a'.repeat(220)}`).join('\n')
  const after = Array.from({ length: 5_000 }, (_, index) => `Proposed line ${index}: ${'b'.repeat(220)}`).join('\n')
  await seedWorkspace(page, { runCount: 1, candidatesPerRun: 2, initialPrompt: before, bestPrompt: after })
  await openWorkspace(page)
  const diff = await showPromptDiff(page)
  await expect(diff).toHaveAttribute('data-exact', 'false')
  await expect(page.getByTestId('prompt-diff-summary')).toHaveAttribute('data-removed', '5000')
  await expect(page.getByTestId('prompt-diff-summary')).toHaveAttribute('data-added', '5000')
  await expect(page.getByTestId('prompt-diff-limited')).toBeVisible()
  await expect(page.getByTestId('prompt-diff-pagination')).toBeVisible()
  const rows = page.getByTestId('prompt-diff-row')
  const assertBounded = async () => {
    const count = await rows.count()
    expect(count).toBeGreaterThan(0)
    expect(count).toBeLessThanOrEqual(200)
    const characters = (await diff.locator('.line-text').allTextContents()).reduce((sum, line) => sum + line.length, 0)
    expect(characters).toBeLessThanOrEqual(32_000)
    expect(await diff.locator('*').count()).toBeLessThan(2_000)
  }
  await assertBounded()
  const firstLine = await rows.first().locator('.line-text').textContent()
  await page.getByTestId('prompt-diff-next').press('Enter')
  await expect(rows.first().locator('.line-text')).not.toHaveText(firstLine!)
  await assertBounded()
  await page.getByTestId('prompt-diff-previous').press('Enter')
  await expect(rows.first().locator('.line-text')).toHaveText(firstLine!)
  await expectNoOverflow(page)
  await attachScreenshot(page, info, 'bounded-long-diff', false)
  expect(await (await showFullPrompt(page)).textContent()).toBe(after)
  const downloaded = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export', exact: true }).click()
  const file = await downloaded
  const exported = JSON.parse(await readFile((await file.path())!, 'utf8'))
  expect(exported.bestPrompt).toBe(after)
  await page.getByRole('button', { name: 'Use this revision', exact: true }).click()
  await expectStored(page, after)
  await page.reload()
  await expect(page.getByTestId('run-status')).toHaveAttribute('data-status', 'completed')
  await showPromptDiff(page)
  await expect(page.getByTestId('prompt-diff')).toHaveAttribute('data-exact', 'false')
  await assertBounded()
  await page.getByRole('button', { name: 'Undo last apply', exact: true }).click()
  await expectStored(page, before)
  await expectNoOverflow(page)
})
