import { readFile } from 'node:fs/promises'
import type { Locator, Page } from '@playwright/test'
import { test, expect, attachScreenshot, expectNoOverflow, openComparison, openPromptMenu, openWorkspace, ORIGINAL_PROMPT, readRecords, seedWorkspace, selectTaskSection, showFullPrompt, showPromptEditor, TASK_ID } from './fixtures'

async function replacePrompt(page: Page, text: string) {
  const editor = page.getByRole('textbox', { name: 'Your prompt', exact: true })
  await expect(editor).toHaveAttribute('contenteditable', 'true')
  await editor.focus()
  await page.keyboard.press('ControlOrMeta+A')
  await page.keyboard.insertText(text)
  await expect(editor).toHaveText(text)
}

async function expectPromptDocument(page: Page, expected: string) {
  const editor = await showPromptEditor(page)
  // CodeMirror renders logical lines as adjacent block elements. The parent's
  // textContent concatenates them without newlines; reconstruct the document
  // from its logical lines rather than normalizing away missing separators.
  await expect.poll(async () => (await editor.locator('.cm-line').allTextContents()).join('\n')).toBe(expected)
}

async function expectPersistedPrompt(page: Page, taskId: string, expected: string) {
  await expect.poll(async () => (await readRecords(page, 'tasks')).find((task) => task.id === taskId)?.initialPrompt).toBe(expected)
}

async function tabTo(page: Page, target: Locator, direction: 'Tab' | 'Shift+Tab' = 'Tab') {
  for (let index = 0; index < 60; index += 1) {
    if (await target.evaluate((element) => element === document.activeElement)) return
    await page.keyboard.press(direction)
  }
  throw new Error(`Could not reach ${await target.getAttribute('aria-label') || await target.textContent()} using ${direction}`)
}

test('fresh prompt → workspace demo setup → run → compare → apply → export', async ({ page }, info) => {
  await page.goto('/')
  const brand = page.getByRole('link', { name: 'Super-Prompt', exact: true })
  await expect(brand).toHaveCount(1)
  await expect(brand).toHaveAttribute('href', '#/')
  await expect.poll(() => brand.locator('img').evaluate((image: HTMLImageElement) => image.complete && image.naturalWidth > 0)).toBe(true)
  await attachScreenshot(page, info, 'branded-home', false)
  await page.getByRole('button', { name: 'Improve prompt', exact: true }).first().click()
  await expect(page.getByTestId('workspace-ready')).toBeVisible()
  await expect(brand).toHaveCount(1)
  await expect.poll(() => brand.locator('img').evaluate((image: HTMLImageElement) => image.complete && image.naturalWidth > 0)).toBe(true)
  await showPromptEditor(page)
  await attachScreenshot(page, info, 'new-task', false)
  await replacePrompt(page, ORIGINAL_PROMPT)
  await attachScreenshot(page, info, 'current-prompt-editor', false)
  await page.getByRole('button', { name: 'Configure models', exact: true }).click()
  const configuration = page.getByRole('dialog', { name: 'Configure models', exact: true })
  await expect(configuration).toBeVisible()
  await attachScreenshot(page, info, 'model-setup', false)
  await configuration.getByRole('button', { name: 'Use demo', exact: true }).click()
  await configuration.getByRole('button', { name: 'Save models', exact: true }).click()
  await expect(configuration).toBeHidden()
  await attachScreenshot(page, info, 'configured-workspace')
  const clickedAt = await page.evaluate(() => performance.now())
  await page.getByRole('button', { name: 'Improve prompt', exact: true }).click()
  await expect(page.getByTestId('run-status')).toHaveAttribute('data-status', 'running')
  const feedbackMs = await page.evaluate((start) => performance.now() - start, clickedAt)
  await attachScreenshot(page, info, 'running-feedback', false)
  await expect(page.getByTestId('run-status')).toHaveAttribute('data-status', 'completed', { timeout: 30_000 })
  await expect(page.getByTestId('result-prompt')).toBeVisible()
  await attachScreenshot(page, info, 'completed-revision', false)
  const best = await showFullPrompt(page)
  await expect(best).not.toHaveText('')
  const winningPrompt = (await best.textContent())!
  expect(winningPrompt).toContain('Before answering')
  await expectNoOverflow(page)
  await attachScreenshot(page, info, 'completed-result')

  await openComparison(page)
  const comparison = page.getByRole('dialog', { name: 'Compare A vs B', exact: true })
  await comparison.getByRole('button', { name: 'Run comparison', exact: true }).click()
  await expect(comparison.getByRole('heading', { name: 'Results', exact: true })).toBeVisible({ timeout: 20_000 })
  await expect(comparison).toContainText('B wins')
  await attachScreenshot(page, info, 'comparison-result')
  await comparison.getByRole('button', { name: 'Close', exact: true }).last().click()

  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export', exact: true }).click()
  const download = await downloadPromise
  expect(download.suggestedFilename()).toMatch(/^super-prompt-.*\.json$/)
  const exported = JSON.parse(await readFile((await download.path())!, 'utf8'))
  expect(exported.bestPrompt).toBe(winningPrompt)
  expect(exported.candidates.length).toBeGreaterThan(1)
  expect(exported.iterations.length).toBeGreaterThan(0)
  await page.getByRole('button', { name: 'Use this revision', exact: true }).click()
  await expectPromptDocument(page, winningPrompt)
  // Separate exact storage assertions prevent the presentation assertion from
  // hiding lost, reordered, or normalized prompt characters/line breaks.
  await expectPersistedPrompt(page, exported.task.id, winningPrompt)
  await page.reload()
  await expect(page.getByTestId('run-status')).toHaveAttribute('data-status', 'completed')
  await expectPromptDocument(page, winningPrompt)
  await expectPersistedPrompt(page, exported.task.id, winningPrompt)
  expect(await readRecords(page, 'runs')).toHaveLength(1)
  const records = await readRecords(page, 'datasets_items')
  expect(records.length).toBeGreaterThanOrEqual(2)
  await info.attach('workflow-measurement', { body: JSON.stringify({ synthetic: true, provider: 'built-in demo', clickToRunningFeedbackMs: feedbackMs, completedRuns: 1, generatedExamples: records.length }, null, 2), contentType: 'application/json' })
})

test('pause survives navigation, resume works, stop is durable', async ({ page }, info) => {
  await seedWorkspace(page)
  await openWorkspace(page)
  await page.getByRole('button', { name: 'Improve prompt', exact: true }).click()
  await expect(page.getByTestId('run-status')).toHaveAttribute('data-status', 'running')
  await page.getByRole('button', { name: 'Pause', exact: true }).click()
  await expect(page.getByTestId('run-status')).toHaveAttribute('data-status', 'paused')
  await selectTaskSection(page, 'History')
  await selectTaskSection(page, 'Improve')
  await expect(page.getByTestId('run-status')).toHaveAttribute('data-status', 'paused')
  await page.getByRole('button', { name: 'Resume', exact: true }).click()
  await expect(page.getByTestId('run-status')).toHaveAttribute('data-status', 'running')
  await page.getByRole('button', { name: 'Stop', exact: true }).click()
  await expect(page.getByTestId('run-status')).toHaveAttribute('data-status', 'stopped')
  await page.reload()
  await expect(page.getByTestId('run-status')).toHaveAttribute('data-status', 'stopped')
  const runs = await readRecords(page, 'runs')
  expect(runs).toHaveLength(1)
  expect(runs[0].status).toBe('stopped')
  await attachScreenshot(page, info, 'stopped-run')
})

test('reloading a live run produces a truthful recoverable stopped state', async ({ page }, info) => {
  await seedWorkspace(page)
  await openWorkspace(page)
  await page.getByRole('button', { name: 'Improve prompt', exact: true }).click()
  await expect(page.getByTestId('run-status')).toHaveAttribute('data-status', 'running')
  await page.reload()
  await expect(page.getByTestId('run-status')).toHaveAttribute('data-status', 'stopped')
  await expect(page.getByRole('button', { name: 'Improve prompt', exact: true })).toBeEnabled()
  const runs = await readRecords(page, 'runs')
  expect(runs).toHaveLength(1)
  expect(runs[0].status).toBe('stopped')
  expect(runs[0].errorMessage).toMatch(/reload|interrupt/i)
  await attachScreenshot(page, info, 'recovered-run')
})

test('latest prompt persists across immediate navigation, reload, and reopening', async ({ page }) => {
  await seedWorkspace(page)
  await openWorkspace(page)
  const afterNavigation = 'This edit must survive immediate tab navigation.'
  await replacePrompt(page, afterNavigation)
  // Intentionally do not wait for the old 500ms debounce before unmounting.
  await selectTaskSection(page, 'History')
  await selectTaskSection(page, 'Improve')
  await expect(page.getByRole('textbox', { name: 'Your prompt', exact: true })).toHaveText(afterNavigation)
  const afterReload = 'This final edit must survive an immediate page reload.'
  await replacePrompt(page, afterReload)
  page.once('dialog', (dialog) => void dialog.accept())
  await page.reload()
  await expect(page.getByRole('textbox', { name: 'Your prompt', exact: true })).toHaveText(afterReload)
  await page.goto('/')
  await page.getByRole('button', { name: /Synthetic prompt fixture/ }).click()
  await openPromptMenu(page)
  await expect(page.getByRole('navigation', { name: 'Prompt navigation', exact: true }).getByRole('link', { name: 'Improve', exact: true })).toHaveAttribute('aria-current', 'page')
  await page.keyboard.press('Escape')
  await expect(page.getByRole('textbox', { name: 'Your prompt', exact: true })).toHaveText(afterReload)
  expect((await readRecords(page, 'tasks')).find((task) => task.id === TASK_ID)?.initialPrompt).toBe(afterReload)
})

test('keyboard dialog trap, prompt-menu routes, and reduced-motion layout', async ({ page }, info) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await seedWorkspace(page, { runCount: 1 })
  await openWorkspace(page)
  const opener = page.getByRole('button', { name: 'Configure models', exact: true })
  await tabTo(page, opener)
  await page.keyboard.press('Enter')
  const dialog = page.getByRole('dialog', { name: 'Configure models', exact: true })
  await expect(dialog).toBeVisible()
  await expect.poll(() => dialog.evaluate((element) => element.contains(document.activeElement))).toBe(true)
  for (const direction of ['Tab', 'Shift+Tab']) {
    for (let index = 0; index < 25; index += 1) {
      await page.keyboard.press(direction)
      expect(await dialog.evaluate((element) => element.contains(document.activeElement))).toBe(true)
    }
  }
  await page.keyboard.press('Escape')
  await expect(dialog).toBeHidden()
  await expect(opener).toBeFocused()

  const menu = page.locator('details.context-menu')
  const menuButton = menu.locator('summary[aria-label="Prompt menu"]')
  await tabTo(page, menuButton, 'Shift+Tab')
  await page.keyboard.press('Enter')
  const navigation = page.getByRole('navigation', { name: 'Prompt navigation', exact: true })
  await expect(navigation).toBeVisible()
  for (const name of ['Improve', 'Overview', 'Examples', 'History']) {
    await expect(navigation.getByRole('link', { name, exact: true })).toBeVisible()
  }
  await attachScreenshot(page, info, 'prompt-more-menu', false)
  await tabTo(page, navigation.getByRole('link', { name: 'Overview', exact: true }))
  await page.keyboard.press('Enter')
  await expect(page).toHaveURL(new RegExp(`/task/${TASK_ID}/overview$`))
  await expect(navigation).toBeHidden()
  await expect(page.locator('#task-panel')).toBeFocused()

  await tabTo(page, menuButton, 'Shift+Tab')
  await page.keyboard.press('Enter')
  await expect(navigation.getByRole('link', { name: 'Overview', exact: true })).toHaveAttribute('aria-current', 'page')
  await page.keyboard.press('Escape')
  await expect(navigation).toBeHidden()
  await expect(menuButton).toBeFocused()
  await page.keyboard.press('Enter')
  await tabTo(page, navigation.getByRole('link', { name: 'Improve', exact: true }))
  await page.keyboard.press('Enter')
  await expect(page).toHaveURL(new RegExp(`/task/${TASK_ID}/improve$`))
  await expect(navigation).toBeHidden()
  await expect(page.getByTestId('result-prompt')).toBeVisible()
  await expectNoOverflow(page)
  expect(await page.evaluate(() => matchMedia('(prefers-reduced-motion: reduce)').matches)).toBe(true)
  const loopingAnimations = await page.evaluate(() => document.getAnimations().filter((animation) => animation.playState === 'running' && animation.effect?.getTiming().iterations === Infinity).length)
  expect(loopingAnimations).toBe(0)
  await attachScreenshot(page, info, 'keyboard-reduced-motion')
})

test('10k examples and 1k runs stay bounded, including the comparison picker', async ({ page }, info) => {
  await seedWorkspace(page, { itemCount: 10_000, runCount: 1_000 })
  await page.goto(`/#/task/${TASK_ID}/dataset`)
  await expect(page.locator('tbody tr')).toHaveCount(10)
  await expect(page.locator('tbody textarea')).toHaveCount(20)
  await expectNoOverflow(page)
  await attachScreenshot(page, info, 'large-dataset-page')
  await selectTaskSection(page, 'History')
  await expect(page.locator('.list > .run')).toHaveCount(20)
  await expect(page.locator('.cand')).toHaveCount(0)
  await page.locator('.list > .run').first().locator('summary').click()
  await expect(page.locator('.cand')).toHaveCount(8)
  await expectNoOverflow(page)
  await selectTaskSection(page, 'Improve')
  await openComparison(page)
  const comparison = page.getByRole('dialog', { name: 'Compare A vs B', exact: true })
  await expect(comparison.getByRole('checkbox')).toHaveCount(20)
  await comparison.getByRole('button', { name: 'Next', exact: true }).click()
  await expect(comparison.getByRole('checkbox')).toHaveCount(20)
  await expect(comparison.locator('.item-input').first()).toContainText('Synthetic example 20:')
  await expectNoOverflow(page)
  await attachScreenshot(page, info, 'large-comparison-picker')
  await page.keyboard.press('Escape')
  await expect(comparison).toBeHidden()
})

test('cancel during slow preparation never creates a run or replaces examples', async ({ page }) => {
  await seedWorkspace(page, { itemCount: 0, providerBaseUrl: 'http://127.0.0.1:4173/__synthetic/slow' })
  await openWorkspace(page)
  const request = page.waitForRequest((request) => request.url().includes('/__synthetic/slow/chat/completions'))
  await page.getByRole('button', { name: 'Improve prompt', exact: true }).click()
  await request
  await page.getByRole('button', { name: 'Cancel preparation', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Improve prompt', exact: true })).toBeEnabled()
  await selectTaskSection(page, 'History')
  await expect(page.getByText('No runs yet', { exact: true })).toBeVisible()
  // Beyond the server's controlled 1500ms response window: a late response must
  // not create examples/run after cancellation or after leaving the workspace.
  await page.waitForTimeout(1800)
  expect(await readRecords(page, 'runs')).toHaveLength(0)
  expect(await readRecords(page, 'datasets_items')).toHaveLength(0)
  await selectTaskSection(page, 'Improve')
  await expect(page.getByRole('button', { name: 'Improve prompt', exact: true })).toBeEnabled()
})

test('provider failure remains visible after reload and can be retried with demo', async ({ page }, info) => {
  await seedWorkspace(page, { providerBaseUrl: 'http://127.0.0.1:4173/__synthetic/fail' })
  await openWorkspace(page)
  await page.getByRole('button', { name: 'Improve prompt', exact: true }).click()
  await expect(page.getByTestId('run-status')).toHaveAttribute('data-status', 'failed')
  await expect(page.getByTestId('run-status')).toContainText('Synthetic provider failure')
  await page.reload()
  await expect(page.getByTestId('run-status')).toHaveAttribute('data-status', 'failed')
  await attachScreenshot(page, info, 'failed-run')
  await page.getByRole('button', { name: 'Configure models', exact: true }).click()
  const configuration = page.getByRole('dialog', { name: 'Configure models', exact: true })
  await configuration.getByRole('button', { name: 'Use demo', exact: true }).click()
  await configuration.getByRole('button', { name: 'Save models', exact: true }).click()
  await page.getByRole('button', { name: 'Improve prompt', exact: true }).click()
  await expect(page.getByTestId('run-status')).toHaveAttribute('data-status', 'completed', { timeout: 30_000 })
  const runs = await readRecords(page, 'runs')
  expect(runs).toHaveLength(2)
  expect(runs.map((run) => run.status).sort()).toEqual(['completed', 'failed'])
})

test('comparison error clears on close/reopen and retry uses changed model settings', async ({ page }) => {
  await seedWorkspace(page, { runCount: 1, itemCount: 2, providerBaseUrl: 'http://127.0.0.1:4173/__synthetic/fail' })
  await openWorkspace(page)
  await openComparison(page)
  const comparison = page.getByRole('dialog', { name: 'Compare A vs B', exact: true })
  await comparison.getByRole('button', { name: 'Run comparison', exact: true }).click()
  await expect(comparison.getByRole('alert')).toContainText('Synthetic provider failure', { timeout: 15_000 })
  await expect(comparison.getByRole('heading', { name: 'Results', exact: true })).toHaveCount(0)
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: 'Configure models', exact: true }).click()
  const configuration = page.getByRole('dialog', { name: 'Configure models', exact: true })
  await configuration.getByRole('button', { name: 'Use demo', exact: true }).click()
  await configuration.getByRole('button', { name: 'Save models', exact: true }).click()
  await openComparison(page)
  await expect(comparison.getByRole('alert')).toHaveCount(0)
  await comparison.getByRole('button', { name: 'Run comparison', exact: true }).click()
  await expect(comparison.getByRole('heading', { name: 'Results', exact: true })).toBeVisible()
  await comparison.getByRole('button', { name: 'Close', exact: true }).last().click()
  await openComparison(page)
  await expect(comparison.getByRole('alert')).toHaveCount(0)
  await expect(comparison.getByRole('heading', { name: 'Results', exact: true })).toHaveCount(0)
  await expect(comparison.getByRole('button', { name: 'Run comparison', exact: true })).toBeEnabled()
})

test('preparation failure replaces old completion status and retry preserves the prior run', async ({ page }, info) => {
  await seedWorkspace(page, { runCount: 1, itemCount: 0, providerBaseUrl: 'http://127.0.0.1:4173/__synthetic/fail' })
  await openWorkspace(page)
  const status = page.getByTestId('run-status')
  await expect(status).toHaveCount(1)
  await expect(status).toHaveAttribute('data-status', 'completed')
  const [previousRun] = await readRecords(page, 'runs')
  expect(previousRun.status).toBe('completed')

  await page.getByRole('button', { name: 'Keep current', exact: true }).click()
  await page.getByRole('button', { name: 'Improve prompt', exact: true }).click()
  await expect(status).toHaveCount(1)
  await expect(status).toHaveAttribute('data-status', 'error')
  await expect(status.getByRole('alert')).toContainText('Synthetic provider failure')
  expect(await readRecords(page, 'runs')).toEqual([previousRun])
  expect(await readRecords(page, 'datasets_items')).toHaveLength(0)

  // Reopening the still-available prior revision must not reintroduce its
  // completed marker alongside the current preparation error.
  await page.getByTestId('run-result').getByRole('button', { name: 'Review changes', exact: true }).click()
  await expect(page.getByTestId('result-prompt')).toBeVisible()
  await expect(status).toHaveCount(1)
  await expect(status).toHaveAttribute('data-status', 'error')
  await expect(status.getByRole('alert')).toContainText('Synthetic provider failure')
  await attachScreenshot(page, info, 'preparation-error-after-completed-run', false)

  await page.getByRole('button', { name: 'Configure models', exact: true }).click()
  const configuration = page.getByRole('dialog', { name: 'Configure models', exact: true })
  await configuration.getByRole('button', { name: 'Use demo', exact: true }).click()
  await configuration.getByRole('button', { name: 'Save models', exact: true }).click()
  await page.getByRole('button', { name: 'Keep current', exact: true }).click()
  await page.getByRole('button', { name: 'Improve prompt', exact: true }).click()
  await expect(status).toHaveAttribute('data-status', 'running')
  await expect(status).toHaveAttribute('data-status', 'completed', { timeout: 30_000 })
  await expect(status).toHaveCount(1)
  const runs = await readRecords(page, 'runs')
  expect(runs).toHaveLength(2)
  expect(runs.find((run) => run.id === previousRun.id)).toEqual(previousRun)
  expect(runs.find((run) => run.id !== previousRun.id)?.status).toBe('completed')
  expect((await readRecords(page, 'datasets_items')).length).toBeGreaterThanOrEqual(2)
})
